export const ADD_TO_WISH = "ADD_TO_WISH";
export const MOVE_TO_CART = "MOVE_TO_CART";
export const REMOVE_FROM_WISH = "REMOVE_FROM_WISH";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_ITEM_IN_WISH = "INCREASE_ITEM_IN_WISH";
export const DECREASE_ITEM_IN_WISH = "DECREASE_ITEM_IN_WISH";
